baseURL = "https://benmurden.github.io/react-native-quick-intro"
languageCode = "en-us"
title = "React Native Quick Intro"
theme = "reveal-hugo"

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true